config/routes.rb
StoreEngine::Application.routes.draw do

  resources :static_pages, :only => :index
  resources :users, :except => [:index, :destroy, :show]
  resources :billing_address
  resources :shipping_address
  resources :sessions, :only => [:new, :create, :destroy]
  resources :stores, :only => [:index, :create]
  resources :products, :only => [:index, :show]
  resources :bids, :only => [:index]

  resources :auctions, :only => [:index, :show] do
    resources :bids, :only =>   [:create]
  end

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'signup', to: 'users#new', as: 'signup'
  get 'create_new_store', to: 'stores#new', as: 'create_new_store'

  get 'profile', :to => 'users#show', as: 'profile'
  get 'profile/orders', :to => 'orders#index', as: 'profile_orders'
  get 'profile/edit', :to => 'users#edit', as: 'edit_profile'



  namespace :admin do
    get "/", to: "stores#index", as: 'home'
    resources :stores
  end

  scope "/:store_id" do

    #get "/", to: "products#index", :as => :store_home
    #match "/" => "products#index", :as => :home

    match 'checkout' => 'orders#new', as: 'checkout'
    match 'checkout/type' => 'orders#type', as: 'checkout_type'

    resources :orders, :except => [:edit, :update, :destroy]

    namespace :store_admin, :path => "/admin" do
      match "/" => "dashboards#show"
      resources :products, :except => :destroy
      resources :members
      resources :stores, :only => [:index, :edit, :update]
      resources :orders, :except => :destroy
      resources :auctions
    end

  end

  root :to => 'static_pages#index'

end

app/controllers/store_admin/auctions_controller.rb
class StoreAdmin::AuctionsController < ApplicationController
  before_filter :require_admin
  layout 'admin'

  def index
    @auctions = Auction.includes(:product).find_all_by_store_id(current_store)
  end

  def new
    @auction = Auction.new
    @auction.build_product
    @auction.payment_options.build
  end

  def create
    @auction = Auction.new(params[:auction])
    date = Auction.parse_expiration_date(params[:auction][:selected_expiration_date])
    @auction.expiration_date = date

    if @auction.save
      redirect_to auction_path(@auction), notice: "Auction Sucessfully Created!"
    else
      render :index
    end
  end
end

app/controllers/store_admin/dashboards_controller.rb
class StoreAdmin::DashboardsController < ApplicationController
  before_filter :require_admin
  layout 'admin'

  def show
    @orders = current_store.orders

    # receieve status from params[:status]
    # selected_orders = Order.all
    # @orders = Order.all
    method = params[:status]

    # if method && Order.respond_to?(method)
    #   @orders = Order.send(method.to_sym)
    # else
    #   @orders = Order.all
    # end
  end

  def edit
    @store = Store.find(params[:store_id])
  end
end

app/controllers/store_admin/members_controller.rb
class StoreAdmin::MembersController < ApplicationController

  before_filter :require_admin
  layout 'admin'

  def index
    @admins = UserStoreRole.where(store_id: current_store.id, role: 'admin').map(&:user)
  end

  def new
    @role = 'admin'
    @member = UserStoreRole.new
  end

  def create
    @user = User.find_by_email(params[:invite][:email])
    if @user
      @user.assign_role(current_store.id, params[:invite][:role])
      logger.debug("Sending Email to existing user")
    else

      logger.debug("Sending Email to new user")
    end

    flash[:notice] = "Member Invited!"
    redirect_to store_admin_members_path
  end

  def destroy

    @user_store_role = UserStoreRole.where(store_id: params[:id], user_id: params[:user]).first
    @user_store_role.destroy


    flash[:notice] = "Member Removed"
    redirect_to store_admin_members_path

  end


  private

  def get_store_users
    @members ||= current_store.users
  end
end

app/controllers/store_admin/orders_controller.rb
class StoreAdmin::OrdersController < ApplicationController

  before_filter :require_admin
  layout 'admin'

  def show
    @order = Order.find(params[:id])
  end

  def index
    @orders = current_store.orders
  end

  def update
    @order = Order.find(params[:id])
    if @order.current_status == "pending"
      @order.cancel
    elsif @order.current_status == "shipped"
      @order.return
    elsif @order.current_status == "paid"
      @order.ship
    end
    redirect_to :back
  end
end

app/controllers/store_admin/products_controller.rb
class StoreAdmin::ProductsController < ApplicationController

  before_filter :require_admin_or_stocker

  layout 'admin'

  def index
    @products = current_store.products
    @orders = current_store.orders
  end

  def new
    @store = current_store
    @product = current_store.products.build
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes params[:product]
      redirect_to store_admin_products_path(current_store), notice: "Product Updated!"
    else
      # flash[:error] = "An error occurred, please try again"
      render :edit
    end
  end

  def create
    @product = Product.new(params[:product].merge({store_id: current_store.id}))
    if @product.save
      redirect_to store_home_path, notice: "Product Added!"
    else
      render :new
    end
  end
end

app/controllers/store_admin/stores_controller.rb
class StoreAdmin::StoresController < ApplicationController
  layout 'admin', only: [:edit, :update]

  before_filter :require_admin, except: :index

  def index
    @stores = current_user.stores
  end

  def edit
    @store ||= current_store
  end

  def show
    @store ||= current_store
  end

  def update
    @store = Store.find_by_path(params[:store_id])

    if @store.update_attributes(params[:store])
      redirect_to store_admin_path, notice: "Store details were successfully updated"
    else
      render :edit
    end
  end
end

app/views/store_admin/members/index.html.haml
- provide(:title, 'Admin Members')
%section#right-pane
  .row.admin-header
    .span12
      %h3
        #{current_store.name.titleize}'s Admins


  #admin-tab.span9
    .row-fluid
      .span12
        .span6
          %h3 Store Admins
        .span6.header-button
          = link_to "Add New Store Admin", new_store_admin_member_path(current_store, role: "admin"),
            method: :get, :class => "admin-primary-button pull-right"

    .row-fluid
      .span12#store-admin-table
        %table.table.table-striped.table-bordered.cart-detail
          %thead
            %tr
              %th.span3 Full Name
              %th.span3 Email
              %th.span3 Role
              %th.span3 Action
          %tbody
            - @admins.each do |admin|
              %tr
                %td= admin.full_name
                %td= admin.email
                %td Admin
                %td= link_to "Remove", store_admin_member_path(current_store, current_store.id, user: admin.id),
                    method: :delete, data: { confirm: 'Are you sure?' }

app/views/store_admin/members/new.html.haml
- provide(:title, 'Add New Admin')

%section#right-pane
  .row.admin-header
    .span12
      %h3
        #{current_store.name.titleize}'s Admins

  .single-form
    = simple_form_for :invite, :url => store_admin_members_path do |f|
      = f.error_notification 
      = f.input :email, label: false, input_html: { placeholder: "Email" }
      = f.hidden_field :role, value: @role
      = f.button :submit, :value => "Add New Admin", :class => "form-primary-button"
      = f.error :base