config/routes.rb
StoreEngine::Application.routes.draw do

  resources :static_pages, :only => :index
  resources :users, :except => [:index, :destroy, :show]
  resources :billing_address
  resources :shipping_address
  resources :sessions, :only => [:new, :create, :destroy]
  resources :stores, :only => [:index, :create]
  resources :products, :only => [:index, :show]
  resources :bids, :only => [:index]

  resources :auctions, :only => [:index, :show] do
    resources :bids, :only =>   [:create]
  end

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'signup', to: 'users#new', as: 'signup'
  get 'create_new_store', to: 'stores#new', as: 'create_new_store'

  get 'profile', :to => 'users#show', as: 'profile'
  get 'profile/orders', :to => 'orders#index', as: 'profile_orders'
  get 'profile/edit', :to => 'users#edit', as: 'edit_profile'



  namespace :admin do
    get "/", to: "stores#index", as: 'home'
    resources :stores
  end

  scope "/:store_id" do

    #get "/", to: "products#index", :as => :store_home
    #match "/" => "products#index", :as => :home

    match 'checkout' => 'orders#new', as: 'checkout'
    match 'checkout/type' => 'orders#type', as: 'checkout_type'

    resources :orders, :except => [:edit, :update, :destroy]

    namespace :store_admin, :path => "/admin" do
      match "/" => "dashboards#show"
      resources :products, :except => :destroy
      resources :members
      resources :stores, :only => [:index, :edit, :update]
      resources :orders, :except => :destroy
      resources :auctions
    end

  end

  root :to => 'static_pages#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :title,
                  :description,
                  :price_in_dollars,
                  :active,
                  :created_at,
                  :updated_at,
                  :price,
                  :slug,
                  :category_ids,
                  :photo_url,
                  :auction_id,
                  :photo


    has_attached_file :photo,
                      styles: { large: '600x600>', thumb: '100x100>'},
                      default_url: 'http://placehold.it/100/100'

  validates_uniqueness_of :title
  validates_presence_of :title, :description

  belongs_to :auction
  has_many :product_categories
  has_many :categories, through: :product_categories

  searchable do
    text :title, boost: 5
    text :description
  end

  def status
    active ? "active" : "retired"
  end

  def to_s
    title
  end

  def price_in_dollars
    price.to_f / 100 if price
  end

  def price_in_dollars=(dollars)
    self.price = dollars.to_f * 100.0
  end

  def categories_list
    self.categories.join(", ")
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @search = Product.search(:include => [:auction]) do
      fulltext params[:search]
    end
    @products = @search.results
  end

end

app/controllers/store_admin/auctions_controller.rb
class StoreAdmin::AuctionsController < ApplicationController
  before_filter :require_admin
  layout 'admin'

  def index
    @auctions = Auction.includes(:product).find_all_by_store_id(current_store)
  end

  def new
    @auction = Auction.new
    @auction.build_product
    @auction.payment_options.build
  end

  def create
    @auction = Auction.new(params[:auction])
    date = Auction.parse_expiration_date(params[:auction][:selected_expiration_date])
    @auction.expiration_date = date

    if @auction.save
      redirect_to auction_path(@auction), notice: "Auction Sucessfully Created!"
    else
      render :index
    end
  end
end

app/controllers/store_admin/dashboards_controller.rb
class StoreAdmin::DashboardsController < ApplicationController
  before_filter :require_admin
  layout 'admin'

  def show
    @orders = current_store.orders

    # receieve status from params[:status]
    # selected_orders = Order.all
    # @orders = Order.all
    method = params[:status]

    # if method && Order.respond_to?(method)
    #   @orders = Order.send(method.to_sym)
    # else
    #   @orders = Order.all
    # end
  end

  def edit
    @store = Store.find(params[:store_id])
  end
end

app/controllers/store_admin/members_controller.rb
class StoreAdmin::MembersController < ApplicationController

  before_filter :require_admin
  layout 'admin'

  def index
    @admins = UserStoreRole.where(store_id: current_store.id, role: 'admin').map(&:user)
  end

  def new
    @role = 'admin'
    @member = UserStoreRole.new
  end

  def create
    @user = User.find_by_email(params[:invite][:email])
    if @user
      @user.assign_role(current_store.id, params[:invite][:role])
      logger.debug("Sending Email to existing user")
    else

      logger.debug("Sending Email to new user")
    end

    flash[:notice] = "Member Invited!"
    redirect_to store_admin_members_path
  end

  def destroy

    @user_store_role = UserStoreRole.where(store_id: params[:id], user_id: params[:user]).first
    @user_store_role.destroy


    flash[:notice] = "Member Removed"
    redirect_to store_admin_members_path

  end


  private

  def get_store_users
    @members ||= current_store.users
  end
end

app/controllers/store_admin/orders_controller.rb
class StoreAdmin::OrdersController < ApplicationController

  before_filter :require_admin
  layout 'admin'

  def show
    @order = Order.find(params[:id])
  end

  def index
    @orders = current_store.orders
  end

  def update
    @order = Order.find(params[:id])
    if @order.current_status == "pending"
      @order.cancel
    elsif @order.current_status == "shipped"
      @order.return
    elsif @order.current_status == "paid"
      @order.ship
    end
    redirect_to :back
  end
end

app/controllers/store_admin/products_controller.rb
class StoreAdmin::ProductsController < ApplicationController

  before_filter :require_admin_or_stocker

  layout 'admin'

  def index
    @products = current_store.products
    @orders = current_store.orders
  end

  def new
    @store = current_store
    @product = current_store.products.build
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes params[:product]
      redirect_to store_admin_products_path(current_store), notice: "Product Updated!"
    else
      # flash[:error] = "An error occurred, please try again"
      render :edit
    end
  end

  def create
    @product = Product.new(params[:product].merge({store_id: current_store.id}))
    if @product.save
      redirect_to store_home_path, notice: "Product Added!"
    else
      render :new
    end
  end
end

app/controllers/store_admin/stores_controller.rb
class StoreAdmin::StoresController < ApplicationController
  layout 'admin', only: [:edit, :update]

  before_filter :require_admin, except: :index

  def index
    @stores = current_user.stores
  end

  def edit
    @store ||= current_store
  end

  def show
    @store ||= current_store
  end

  def update
    @store = Store.find_by_path(params[:store_id])

    if @store.update_attributes(params[:store])
      redirect_to store_admin_path, notice: "Store details were successfully updated"
    else
      render :edit
    end
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/store_admin/products/_form.html.haml
= simple_form_for [:store_admin, @product], :html => {:multipart => true} do |f|
  = f.error_notification
  = f.input :title, input_html: {class: "span6"}
  = f.input :description, input_html: {class: "span6", rows: 10}
  = f.input :price_in_dollars
  = f.input :active, as: :radio_buttons
  = f.association :categories, as: :check_boxes, :item_wrapper_class => 'inline'
  = f.input :photo, as: :file, label: "Upload pic"
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = submit_tag 'Cancel', :type => :reset, :class => "btn btn-danger"
  = f.error :base

app/views/store_admin/products/edit.html.haml
- provide(:title, 'Admin Edit Product')

%section#right-pane 
  .row.admin-header
    .span12
      %h3
        #{current_store.name.titleize}'s Products

  .row-fluid
    .span8
      .span6
        %h4 Edit Existing Product
  -# = render 'form'
  = simple_form_for [:store_admin, @product],
    :url => store_admin_product_path(current_store, @product), 
    :method => :put, :html => {:multipart => true} do |f|

    = f.error_notification
    = f.input :title, input_html: {class: "span6"}
    = f.input :description, input_html: {class: "span6", rows: 10}
    = f.input :price_in_dollars
    = f.input :active, as: :radio_buttons
    = f.association :categories, as: :check_boxes, :item_wrapper_class => 'inline'
    = f.input :photo, as: :file, label: "Upload pic"
    .form-actions
      = f.button :submit, :class => 'btn-primary'
      = submit_tag 'Cancel', :type => :reset, :class => "btn btn-danger"
    = f.error :base

app/views/store_admin/products/index.html.haml
- provide(:title, 'Admin Products')
%section#right-pane
  .row.admin-header
    .span12
      %h3
        #{current_store.name.titleize}'s Products

  #admin-tab.span9
    .row-fluid
      .span12
        .span6
        .span6.header-button
          = link_to "Add New Product", new_store_admin_product_path(current_store), method: :get,
            :class => "admin-primary-button pull-right"

    .row-fluid
      .span12#store-admin-table
        %table.table.table-striped.table-bordered.cart-detail
          %thead
            %tr
              %th.span1 Product
              %th.span3 Title
              %th.span4 Description
              %th.span2 Price
              %th.span2 Action
          %tbody
            - @products.each do |product|
              %tr
                %td= image_tag product.photo.url
                %td= product.title
                %td= product.description
                %td= number_to_currency(product.price_in_dollars)
                %td= link_to "edit", edit_store_admin_product_path(current_store,product)

  :javascript
    $(document).ready(function(){
      var something = window.location.toString().split('/')[5];
      if (something != null) {
        $('.' + something).addClass('active');
        $('.dashboard').removeClass('active');
      }
    })

app/views/store_admin/products/new.html.haml
- provide(:title, 'Admin Add New Product')

%section#right-pane 
  .row.admin-header
    .span12
      %h3
        #{current_store.name.titleize}'s Products


  .row-fluid
    .span12
      .span6
        %h4 Add New Product
  = render 'form'

app/views/store_admin/products/show.html.haml
- provide(:title, 'Admin Product Detail')
.row-fluid
  .span12
    .span6
      %h3 Product Name