config/routes.rb
StoreEngine::Application.routes.draw do

  resources :static_pages, :only => :index
  resources :users, :except => [:index, :destroy, :show]
  resources :billing_address
  resources :shipping_address
  resources :sessions, :only => [:new, :create, :destroy]
  resources :stores, :only => [:index, :create]
  resources :products, :only => [:index, :show]
  resources :bids, :only => [:index]

  resources :auctions, :only => [:index, :show] do
    resources :bids, :only =>   [:create]
  end

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'signup', to: 'users#new', as: 'signup'
  get 'create_new_store', to: 'stores#new', as: 'create_new_store'

  get 'profile', :to => 'users#show', as: 'profile'
  get 'profile/orders', :to => 'orders#index', as: 'profile_orders'
  get 'profile/edit', :to => 'users#edit', as: 'edit_profile'



  namespace :admin do
    get "/", to: "stores#index", as: 'home'
    resources :stores
  end

  scope "/:store_id" do

    #get "/", to: "products#index", :as => :store_home
    #match "/" => "products#index", :as => :home

    match 'checkout' => 'orders#new', as: 'checkout'
    match 'checkout/type' => 'orders#type', as: 'checkout_type'

    resources :orders, :except => [:edit, :update, :destroy]

    namespace :store_admin, :path => "/admin" do
      match "/" => "dashboards#show"
      resources :products, :except => :destroy
      resources :members
      resources :stores, :only => [:index, :edit, :update]
      resources :orders, :except => :destroy
      resources :auctions
    end

  end

  root :to => 'static_pages#index'

end

app/views/shared/_admin_menu.html.haml
#admin
  .row-fluid
    .span12
      .page-header
        %h1 Administration Portal
  .row-fluid
    .tabbable
      %ul.nav.nav-tabs
        = admin_header_link 'Dashboard', admin_dashboard_path
        = admin_header_link 'Manage Orders', admin_orders_path
        = admin_header_link 'Manage Products', admin_products_path
        = admin_header_link 'Manage Categories', admin_categories_path
        = admin_header_link 'Edit Store Details', admin_edit_path
        = admin_header_link 'Admin Profile', "#"

app/views/shared/_admin_navbar.html.haml
%header.admin-header
  .navbar.navbar-fixed-left
    .navbar
      .navbar-inner
        = link_to 'Shopmazing', root_path, class: "brand admin-brand"
        %ul#admin-menu
          %li= admin_navbar_link 'Dashboard', store_admin_path, %w( admin_header_link dashboard )

          %li= admin_navbar_link 'Orders', store_admin_orders_path(current_store), %w( admin_header_link dashboard )
          %li= admin_navbar_link 'Auctions', store_admin_auctions_path(current_store), %w( admin_header_link dashboard )
          %li= admin_navbar_link 'Admins', store_admin_members_path(current_store), %w( admin_header_link dashboard )
          %li= admin_navbar_link 'Settings', edit_store_admin_store_path(current_store, current_store.id), %w( admin_header_link dashboard )
          %li=link_to 'Your Profile', profile_path, class: "admin_header_link settings"
          %li=link_to 'Logout', logout_path, class: "admin_header_link settings"

app/views/shared/_brand_header.html.haml
.row
  .logo-banner.pull-left.span12
    .span6.logo
      %h1
        %a{:href => "/"}
          = image_tag("http://store-engine.s3.amazonaws.com/assets/Cloak_and_DaggerSmall.png")
    .span6
      .cart_link.pull-right
        %span

app/views/shared/_flash_messages.html.haml
- if flash
  .row-fluid
    .span7.offset3
      - flash.each do |name, msg|
        %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
          %a.close{"data-dismiss" => "alert"} x
          = msg

app/views/shared/_footer.html.haml
.row-fluid.footer
  .span4
    %tr
      %td
      %td
      %td
      %td
      %td
    %h3 Information
    %ul
      %li
        %a{:href => "#"} Contact
      %li
        %a{:href => "#"} Delivery
      %li
        %a{:href => "#"} FAQ
      %li
        %a{:href => "#"} Terms and Conditions
  .span4
    %h3 Stay in Touch
    %ul
      %li
        %a{:href => "#"} Facebook
      %li
        %a{:href => "#"} Twitter
      %li
        .control-group
          .controls
            .input-prepend.input-append
              .span.add-on
                %i.icon-envelope
              %input.span6.appendedPrependedInput{:placeholder => "Enter your email", :type => "text"}/
              %input.btn{:name => "submit", :type => "submit", :value => "Subcribe"}/
  .span4
    %h3 Other stuff
    %ul
      %li
        %a{:href => "#"} Link
      %li
        %a{:href => "#"} Link
      %li
        %a{:href => "#"} Link
      %li
        %a{:href => "#"} Link

app/views/shared/_hero_unit.html.haml
%section
  .hero-unit
    .primary-message
      %h2 Sell Your Products Online
      %h3 without the hassle.
    %a.primary-button.between-sections{:href => new_user_path}
      Sign Up To Create Your Free Shopmazing Store

app/views/shared/_navbar.html.haml
%header
  .navbar.navbar-fixed-top
    .navbar
      .navbar-inner
        .container
          - if current_store
            %a.brand{:href => "/"}= current_store.name
          - else
            %a.brand{:href => "/"} Shopmazing
          %a.brand{:href => "/auctions"} Auctions



          %ul.nav.pull-right
            - if current_user  
              %li
                / %p Welcome #{current_user.full_name}
              %li= link_to "My Account", profile_path
              %li= link_to "Logout", logout_path
            - else
              %li= link_to "Log In", new_session_path
              %li= link_to "Sign Up", new_user_path

          = form_tag( '/products', :method => 'get', :class => 'navbar-search') do
            = text_field_tag :search, params[:search], :placeholder => 'Search', :class => 'search-query'
            = submit_tag 'Search', :style => "position: absolute; left: -9999px; width: 1px; height: 1px;"

app/views/shared/_profile_navbar.html.haml
%header.admin-header
  .navbar.navbar-fixed-left
    .navbar
      .navbar-inner
        = link_to 'Shopmazing', root_path, class: "brand admin-brand"
        -# %a.brand.admin-brand{:href => "#"} Shopmazing
        %ul#admin-menu
          %li= admin_navbar_link 'Profile', profile_path, %w( admin_header_link dashboard )
          %li= admin_navbar_link 'Purchases', profile_orders_path, %w( admin_header_link orders )
          %li= admin_navbar_link 'Your Bids', bids_path, %w( admin_header_link)

          - if current_user.stores.count > 0
            %li
              = admin_navbar_link 'Your Stores', stores_path, %w( admin_header_link)

          - if current_user.is_super_admin?
            %li
              =link_to 'Platform Admin', admin_home_path, class: "admin_header_link"

          %li
            =link_to 'Logout', logout_path, class: "admin_header_link"

        =link_to "Create New Store", create_new_store_path, class: "admin-primary-button admin-cta"

app/views/shared/_signup_flash_messages.html.haml
- if @user.errors.any?
  .alert.alert-error.span8.offset3
    %p
      #{pluralize(@user.errors.count, "problem")} with your registration:
      .errors
      - @user.errors.full_messages.each do |msg|
        %li= msg 

app/views/shared/_static_navbar.html.haml
%header
  .navbar.navbar-fixed-top
    .navbar
      .navbar-inner
        .container
          %a.brand{:href => "/"} Shopmazing
          %a.brand{:href => "/auctions"} Auctions
          %ul.nav
            - if current_user
              %li
                = link_to "My Account", profile_path
              %li
                = link_to "Logout", logout_path
            - else
              %li
                = link_to "Log In", new_session_path
              %li
                = link_to "Sign Up", new_user_path

          = form_tag( '/products', :method => 'get', :class => 'navbar-search') do
            = text_field_tag :search, params[:search], :placeholder => 'Search', :class => 'search-query'
            = submit_tag 'Search', :style => "position: absolute; left: -9999px; width: 1px; height: 1px;"

app/views/shared/_sub_menu.html.haml
.row-fluid
  - if categories
    .span12.nav-menus
      %ul.nav.nav-pills
        %li
          = link_to 'All Products', products_path
        - categories.each do |category|
          %li
            = link_to category.name, category_path(category)

app/views/shared/_super_admin_navbar.html.haml
%header.admin-header
  .navbar.navbar-fixed-left
    .navbar
      .navbar-inner
        = link_to 'Shopmazing', root_path, class: "brand admin-brand"
        %ul#admin-menu
          %li
            =link_to 'Dashboard', admin_home_path, class: "admin_header_link dashboard active"
          %li
            =link_to 'Profile', profile_path
          %li
            =link_to 'Logout', logout_path