config/routes.rb
StoreEngine::Application.routes.draw do

  resources :static_pages, :only => :index
  resources :users, :except => [:index, :destroy, :show]
  resources :billing_address
  resources :shipping_address
  resources :sessions, :only => [:new, :create, :destroy]
  resources :stores, :only => [:index, :create]
  resources :products, :only => [:index, :show]
  resources :bids, :only => [:index]

  resources :auctions, :only => [:index, :show] do
    resources :bids, :only =>   [:create]
  end

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'signup', to: 'users#new', as: 'signup'
  get 'create_new_store', to: 'stores#new', as: 'create_new_store'

  get 'profile', :to => 'users#show', as: 'profile'
  get 'profile/orders', :to => 'orders#index', as: 'profile_orders'
  get 'profile/edit', :to => 'users#edit', as: 'edit_profile'



  namespace :admin do
    get "/", to: "stores#index", as: 'home'
    resources :stores
  end

  scope "/:store_id" do

    #get "/", to: "products#index", :as => :store_home
    #match "/" => "products#index", :as => :home

    match 'checkout' => 'orders#new', as: 'checkout'
    match 'checkout/type' => 'orders#type', as: 'checkout_type'

    resources :orders, :except => [:edit, :update, :destroy]

    namespace :store_admin, :path => "/admin" do
      match "/" => "dashboards#show"
      resources :products, :except => :destroy
      resources :members
      resources :stores, :only => [:index, :edit, :update]
      resources :orders, :except => :destroy
      resources :auctions
    end

  end

  root :to => 'static_pages#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :display_name,
                  :email,
                  :full_name,
                  :password,
                  :password_confirmation,
                  :store_id,
                  :store_name,
                  :stripe_token,
                  :card_number,
                  :card_code,
                  :card_month,
                  :card_year

  attr_accessor :store_name, :stripe_token, :card_number, :card_code, :card_month, :card_year

  before_save :generate_token, if: :card_number_exists?
  before_save :update_stripe, if: :stripe_token_exists?

  validates_uniqueness_of :email
  validates_presence_of :full_name, :email, :password
  validates :display_name, :length => { :minimum => 2,
    :maximum => 32 }, :allow_blank => true

  has_many :user_store_roles
  has_many :stores, :through => :user_store_roles
  has_many :bids


  def assign_super_admin
    self.super_admin = true
    self.save
  end

  def is_super_admin?
    self.super_admin
  end

  def valid_credit_card?
    self.last_4_digits.present?
  end

  def assign_role(store_id, role)
    UserStoreRole.find_or_initialize_by_user_id_and_store_id(user_id: self.id,
                                                             store_id: store_id).update_attributes(role: role)
  end

  def stripe_description
    "#{full_name} #{email}"
  end

  def generate_token
    card_token = Stripe::Token.create(
      :card => {
      :number => card_number,
      :exp_month => card_month.to_i,
      :exp_year => card_year.to_i,
      :cvc => card_code.to_i
    },
    )
    self.stripe_token = card_token.id

  rescue Stripe::StripeError => e
    logger.error "StripeError: " + e.message
    errors.add :base, "#{e.message}."
    false
  end

  def update_stripe
    if customer_id.nil?
      if !stripe_token.present?
        raise "An unexpected error occured while processing your request"
      end

      customer = Stripe::Customer.create(
        email: email,
        description: stripe_description,
        card: stripe_token
      )
    else
      customer = Stripe::Customer.retrieve(customer_id)
      if stripe_token.present?
        customer.card = stripe_token
      end

      customer.email = email
      customer.description = stripe_description
      customer.save
    end

    self.last_4_digits = customer.active_card.last4
    self.customer_id = customer.id
    self.stripe_token = nil

  rescue Stripe::StripeError => e
    logger.error "StripeError: " + e.message
    errors.add :base, "#{e.message}."
    self.stripe_token = nil
    false
  end

  private

  def stripe_token_exists?
    stripe_token.present?
  end

  def card_number_exists?
    card_number.present?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'profile'

  before_filter :require_current_user, only: [:show, :edit, :update]

  def show
    @user = User.find(current_user.id)
  end

  def new
    @user = User.new
    render :layout => 'signup'
  end

  def create
    @user = User.new(params[:user].merge(params[:date]))
    if @user.save
      UserMailer.signup_confirmation_email(@user).deliver
      session[:user_id] = @user.id

      if session[:bid_data] && session[:bid_data][:auction_id]
        route_user(@user)
      else
        flash[:notice] = "Thanks for signin up! Click here to make changes to your account:
                        #{self.class.helpers.link_to( 'Edit Your Account', edit_profile_path) }".html_safe
        redirect_to auctions_path
      end
    else
      flash.now[:alert] = "You entered invalid information, please try again"
      render :new, :layout => 'signup'
    end
  end


  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user].merge(params[:date]))
      if session[:bid_data] && session[:bid_data][:auction_id]
        route_user(@user)
      else
        redirect_to profile_path, notice: "Profile updated!"
      end
    else
      render :edit
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper


end

app/views/admin/users/_form.html.haml
= simple_form_for @user do |f|
  = f.error_notification
  = f.input :phone
  = f.input :receive_sms

app/views/admin/users/edit.html.haml
.row-fluid
  %ul.breadcrumb
    %li
      = link_to "Home", "/"
      %span.divider /
    %li.active
      My Account
.row-fluid
  .tabbable
    %ul.nav.nav-tabs
      %li.active
        = link_to "Profile", @user
      %li
        = link_to "Past Orders", orders_path
= simple_form_for @user do |f|
  = f.error_notification
  = f.input :full_name
  = f.input :email
  = f.input :display_name
  = f.simple_fields_for :phone_number do |p|
    = p.input :phone
    = p.input :receive_sms, label: "Receive SMS?", as: :radio_buttons, :item_wrapper_class => 'inline'
  = f.input :password
  = f.input :password_confirmation
  = f.error :base
  %div
    = f.button :submit, :value => "Update Profile", :class => "btn-primary"

app/views/admin/users/new.html.haml
#signup
  .row-fluid
    .span6.offset3
      %h2.text-center Create Your Store
      = link_to "Already registered? Log in here", login_path, :class => 'text-center'
      = simple_form_for :store do |f|
        = f.error_notification
        = f.input :name
        =f.simple_fields_for :users do |u|
          = u.input :full_name
          = u.input :email
          = u.input :display_name
          = u.input :password
          = u.input :password_confirmation
        = f.button :submit, :value => "Register", :class => "btn-primary"
        = f.error :base

app/views/admin/users/show.html.haml
.row-fluid
  %ul.breadcrumb
    %li
      = link_to "Home", "/"
      %span.divider /
    %li.active
      My Account
.row-fluid
  .tabbable
    %ul.nav.nav-tabs
      %li.active
        = link_to "Profile", admin_user_path(@user)
      %li
        = link_to "Past Orders", orders_path
.row-fluid
  %ul.profile
    %li
      .span8
        %p.span3.header Full Name
        %p.span5= @user.full_name
    %li
      .span8
        %p.span3.header Email
        %p.span5= @user.email
    %li
      .span8
        %p.span3.header Display Name
        %p.span5= @user.display_name
    %li
      .span8
        = link_to "Update Profile", edit_admin_user_path(@user)